# 暴露端口
server:
  port: 8001

# 程序名称
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.161.195:3306/cloud_study?serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# mybatis configure
mybatis:
  type-aliases-package: top.bitqian.springcloud.entity
  mapper-locations: classpath:mapper/*.xml

