# gateway --> 路由 断言 过滤器
server:
  port: 9527

# 网关配置
spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:

      discovery:
        locator:
          enabled: true # 开启从注册中心获取动态路由的功能。利用微服务名进行路由。

      routes:
        - id: payment_routh1 # 路由的id 没有固定规则但是要求唯一 配合服务名称
          # uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 根据服务名进行路由
          predicates:
          - Path=/payment/get/** # 路径像匹配的进行断言~

        - id: payment_routh2 # 路由的id 没有固定规则但是要求唯一 配合服务名称
          # uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
          - Path=/payment/lb/** # 路径像匹配的进行断言~
            # 新增断言配置
            # https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.2.1.RELEASE/reference/html/#gateway-request-predicates-factories
          - After=2020-12-13T11:37:03.340+08:00[Asia/Shanghai] # 必须在这个时间之后
          # - Cookie=username, adorable # 测试      curl --cookie "username=adorable" localhost:9527/payment/lb
          # - Header=X-Request-Id, \d+ # 属性必须是整数 curl --header "X-Request-Id:99" localhost:9527/payment/lb
          # - Query=age  # curl localhost:9527/payment/lb?age=11
          # - Host=**.adorable.cn,**.adorable.top # curl localhost:9527/payment/lb -H "host:bitqian.lovely.adorable.top"


# gateway 入驻eureka~
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka




