# hystrix
server:
  port: 8001


eureka:
  client:
    register-with-eureka: true # 向注册中心注册自己
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-provider-hystrix-payment
